source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!
target 'GYVideo' do
    
    pod 'Alamofire','~> 4.2.0'
    pod 'SnapKit', '~> 3.1.2'
    # pod 'SwiftDrawEnum'
    pod 'GYNetWorking','~> 0.0.9'
    pod 'DGElasticPullToRefresh','~> 1.1'
    pod 'ObjectMapper','~> 2.2.2'
    pod 'SDWebImage', '~> 3.8.2'
    pod 'MJRefresh','~> 3.1.12'
    pod 'GYNavTranstion','~> 0.0.2'
    pod 'EZPlayer' 
end
