source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!
target 'GYVideo' do
    
    pod 'Alamofire'
    pod 'SnapKit', '~> 3.1.2'
    # pod 'SwiftDrawEnum'
    pod 'GYNetWorking','~> 0.0.9'
    pod 'DGElasticPullToRefresh'
end
